### ISSUE TITLE
[Question] iGPU UHD630 patching: no 4k output

### ISSUE THREAD

**Issue by kirintwn** [ruibeard/OpenCore-ASRock-Z490M-ITX-ac#2]
Hi, I am using almost same spec with yours except that my CPU is i5-10400 (same iGPU UHD630). I wonder how you managed to patch the framebuffer to make it work.

At first I followed the Dortania guide but would the installation would eventually become black screen (no signal).  Then I copy paste your framebuffer patching including faking `device-id`, and it magically works!

Now that both Displayport & HDMI can run 2k * 60 hz, but somehow there doesn't exists a 4k resolution option (I'm using a 4k monitor).

I have tried the following:
1. increase the pre-allocated shared memory for iGPU to 1024MB
2. add `framebuffer-unifiedmem` to `DeviceProperties` with value `00000080` (I can see 2GB in About This Mac)
3. add `dpcd-max-link-rate` & `enable-dpcd-max-link-rate-fix` to `DeviceProperties`
4. add `-cdfon -igfxmlr` to boot args

And sadly, still no 4k options for me. Can your rig output at 4k? Or do you have any idea how to fix this?

Below is my spec:

### Hardware List

* ASRock Z490M-ITX/ac
* Intel i5 10400 
  * UHD Graphics 630
* Micron Crucial 16GB DDR4-3200 * 2
* ADATA XPG SX8200Pro 512G
* Fenvi BCM94360NG
* InWin Chopin

### Software List

* OpenCore 0.6.3
* MacOS Big Sur 11.0.1 (Upgraded directly from Catalina 10.15.7)
* SMBios: IMac20,1

Thank you!

**Comment by ruibeard** [comment]
Hi. The framebuffer thing I went to the whatever green docs and tried a bunch of stuff until it worked. 
For the resolution I haven't done anything in particular. Just those con0 and con1 and device ID. I'm using a 3840x1080 49" it works in both HDMI and DP. No HDMI audio though couldn't figure out the problem.

You could try to copy paste the section PciRoot(0x0)/Pci(0x2,0x0) of my config list and see if it works. Or even my entire folder just to try. As you use pretty the same architecture.

**Comment by kirintwn** [comment]
Thanks for the quick reply, I will try your whole EFI on my rig to see if it works.

Just out of curious, did you stuck with black screen in the installation without the framebuffer patching too?

BTW, you probably want to mask `SystemUUID` & `SystemSerialNumber` in your `config.plist`.

**Comment by ruibeard** [comment]
Well it started with black screen until I found the correct combination of settings. When I found it the installation went smooth. No further need to fix  different configs as I was anticipating tbh.
Oh thanks for heads up. I'm using a different serial and uuid anyway.

**Comment by ruibeard** [comment]
Your cpu has this `Device ID 0x9BC8 / 0x9BC5`  for the graphics card while mine only has the `Device ID 0x9BC`. This hex pairs would need to be flipped like C89B0000 those zeros are just to fill. Even though they both have the Hd630 yours can have a different device ID that the config needs to match. I know that's not great help though, but its a place to start. 
Let me know if I can help any further. 
Cheers

**Comment by kirintwn** [comment]
Hi, I have tried to use your whole EFI partition but still in vain.
However, I found this guy's [repo](https://github.com/Xmingbai/asrock-Z490M-itx-ac-hackintosh-Opencore) today, and copy the EFI from his release. Everything seems to work! including HDMI 4k output.

I haven't test HDMI audio though, but you may give it a shot. The repo's docs & tutorials are all in mandarin, let me know if you need any help for translation.

Below is his `PciRoot(0x0)/Pci(0x2,0x0)` looks like:
![image](https://user-images.githubusercontent.com/11881669/103917010-14990580-5148-11eb-85e1-9718b9a99eae.png)

Thanks again for your help!

**Comment by ruibeard** [comment]
Hi, I've also tried his config and it also works. He's using the same `AAPL,ig-platform-id` and `device-id` as I was. 
W=He combined the 
`framebuffer-conX-busid` + `framebuffer-con0-type` + `framebuffer-conX-flags` into `framebuffer-con0-alldata` that's why it looks a bit different. His way it's probably better. 

Anyway my config was working for my hardware before anyway. I'm using a 4k DP monitor since the beginning.

Tbh I was hopping his config would fix my HDMI audio output, but unfortunately not. 

Thanks for sharing. 👍
