### ISSUE TITLE
Remove FAKEPCIID and set DevicePropreties according to opencore guide

### ISSUE THREAD

**Issue by watzeedzad** [ruibeard/OpenCore-ASRock-Z490M-ITX-ac#3]
Hi ruibeard,

I've came across to you repo since I have similar hw but I didn't use iGPU tho.

According to opencore guide you should set your DevicePropreties of iGPU to something like this

Key | Type | Value
-- | -- | --
AAPL,ig-platform-id | Data | 07009B3E
framebuffer-patch-enable | Data | 01000000
framebuffer-stolenmem | Data | 00003001

(This is an example for a desktop UHD 630 without a dGPU and no BIOS options for iGPU memory)

For more info please visit: https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties

And since you use whatevergreen, according to their repo they insist to remove FakePCIID_xxxx.kext

---

Hope this fix your HDMI audio issue.

BTW. When you share your EFI of your system, you should remove Serial, Board Serial, and SmUUID for your own sake.

**Comment by ruibeard** [comment]
Hi, 

In an attempt to try to fix the problem I tried to had a few more settings that are currently in my repo.

I did now just use the ones you suggest and removed all `FakePCI...kext, exactly like your table. 
Unfortunately still not HDMI audio, either using the HDMI or DP port. 

I did removed the serial number from the code now. But I was using a different one anyway. 

Really appreciate you reaching out and try to help. 
Thank you :)
